/**
 * taken from
 * https://github.com/mui-org/material-ui-docs/blob/latest/docs/src/pages/components/material-icons/synonyms.js
 */
const synonyms: { [key: string]: string } = {
  "access_alarm": "clock time",
  "access_alarms": "clock time",
  "accessibility": "accessible body help human person user",
  "accessibility_new": "accessible arms body help human person user",
  "accessible": "accessibility body help human person user wheelchair",
  "accessible_forward": "accessibility body help human person wheelchair",
  "access_time": "clock time",
  "account_balance": "bank building court money payment structure temple transaction",
  "account_balance_wallet": "money payment transaction",
  "account_box": "avatar person profile square thumbnail user",
  "account_circle": "avatar person profile thumbnail user",
  "account_tree": "sitemap project",
  "ac_unit": "freeze snowflake",
  "add": "create item new plus",
  "add_alarm": "clock plus time",
  "add_alert": "announcement bell callout information notification plus reminder",
  "add_a_photo": "camera",
  "add_box": "create new plus square",
  "add_circle": "create new plus",
  "add_circle_outline": "create new plus",
  "add_location": "gps",
  "add_shopping_cart": "checkout plus",
  "add_to_photos": "plus",
  "add_to_queue": "backlog display lineup monitor plus television watch",
  "adjust": "circle",
  "airline_seat_flat": "bed sleep",
  "airline_seat_flat_angled": "bed sleep",
  "airline_seat_individual_suite": "bed sleep",
  "airplanemode_active": "flying",
  "airplanemode_inactive": "flying",
  "airplay": "apple arrow connect control device monitor screen signal television",
  "airport_shuttle": "bus car vehicle",
  "alarm": "clock countdown time",
  "alarm_add": "clock plus time",
  "alarm_off": "clock disabled stop time",
  "alarm_on": "checkmark clock enabled ready start time",
  "album": "artist cd music play record track vinyl",
  "all_inbox": "delivery email letter post send",
  "all_inclusive": "infinite",
  "all_out": "arrows circle directional expand shape",
  "android": "brand character logo mascot operating system toy",
  "announcement": "alert balloon bubble chat comment exclamation message news speech",
  "apartment": "building",
  "apple": "brand logo",
  "apps": "grid homescreen icons",
  "arrow_back": "left",
  "arrow_back_ios": "left",
  "arrow_right_alt": "pointing shape",
  "arrow_upward": "submit",
  "art_track": "display format insert",
  "aspect_ratio": "expand image monitor resolution scale screen size square",
  "assessment": "analytics bars chart graph measure metrics tracking report",
  "assignment": "article clipboard document task text writing",
  "assignment_ind": "clipboard document person profile task user",
  "assignment_late": "alert announcement clipboard exclamation task",
  "assignment_return": "arrow clipboard left point task",
  "assignment_returned": "arrow clipboard down point task",
  "assignment_turned_in": "checkmark clipboard complete done finished task",
  "assistant": "chat comment star",
  "attach_file": "item paperclip",
  "attachment": "file item paperclip",
  "attach_money": "cash currency dollar finance price profit sale",
  "audiotrack": "note",
  "autorenew": "arrows cached inprogress loader loading refresh rotate status pending",
  "av_timer": "clock countdown minutes seconds stopwatch",
  "backspace": "clear delete remove",
  "backup": "arrow cloud point submit upload",
  "bar_chart": "anlytics graph",
  "bathtub": "clean shower",
  "battery_alert": "exclamation",
  "battery_charging_full": "lightning",
  "battery_unknown": "question",
  "beach_access": "parasol sun umbrella",
  "beenhere": "checkmark",
  "biotech": "test",
  "block": "allowed banned cancel disable not",
  "bluetooth": "network wireless",
  "bluetooth_connected": "network wireless",
  "bluetooth_disabled": "network wireless",
  "bluetooth_searching": "network wireless",
  "blur_circular": "circle",
  "book": "bookmark reading blog",
  "bookmark": "favorite remember save",
  "bookmark_border": "favorite outline remember save",
  "bookmarks": "remember save",
  "border_color": "create marker pencil",
  "branding_watermark": "emblem format identity logo stamp",
  "brightness_2": "moon night",
  "brightness_3": "moon night",
  "brightness_4": "dark moon night sun",
  "brightness_5": "sun",
  "brightness_6": "sun",
  "brightness_7": "sun light",
  "broken_image": "picture",
  "brush": "paint",
  "bubble_chart": "analytics graph",
  "bug_report": "animal file insect issue ticket",
  "build": "spanner tool wrench",
  "burst_mode": "image picture",
  "business": "address apartment building company flat office structure",
  "business_center": "briefcase suitcase",
  "cached": "arrows inprogress loader loading refresh reload renew rotate",
  "cake": "birthday pie",
  "calendar_today": "date event month remember reminder week",
  "calendar_view_day": "month remember reminder today week",
  "call": "device mobile phone talk",
  "call_end": "device mobile phone talk",
  "call_made": "arrow device mobile",
  "call_merge": "arrow device mobile",
  "call_missed": "arrow device mobile",
  "call_missed_outgoing": "arrow device mobile",
  "call_received": "arrow device mobile",
  "call_split": "arrow device mobile",
  "call_to_action": "alert bar cta information message notification",
  "camera_enhance": "lens photo picture quality",
  "cancel": "close cross disable status",
  "cancel_presentation": "close device screen share x",
  "card_giftcard": "certificate creditcard present",
  "card_membership": "certificate creditcard subscription",
  "card_travel": "creditcard membership miles trip",
  "casino": "dice",
  "cast": "chromecast",
  "cast_connected": "chromecast",
  "change_history": "shape triangle",
  "chat": "bubble comment message speech talk text",
  "chat_bubble": "comment message speech talk text",
  "chat_bubble_outline": "comment message speech talk text",
  "check": "checkmark success tick",
  "check_box": "checkmark square success tick",
  "check_box_outline_blank": "checkmark square tick",
  "check_circle": "checkmark complete done finished success tick",
  "check_circle_outline": "checkmark complete done finished success tick",
  "chevron_left": "arrow",
  "chevron_right": "arrow",
  "child_care": "baby",
  "child_friendly": "baby",
  "chrome_reader_mode": "text",
  "class": "category item",
  "clear": "allowed cancel cross disable not times x",
  "clear_all": "delete document erase format lines list notifications wipe",
  "close": "allowed cancel cross disable not times x status",
  "closed_caption": "accessible decoder language subtitles",
  "cloud": "weather",
  "cloud_done": "checkmark",
  "code": "brackets css developer engineering html parenthesis platform",
  "colorize": "color picker pipette",
  "comment": "bubble chat document message note",
  "commute": "car train transportation vehicle",
  "compare_arrows": "directional facing pointing",
  "computer": "laptop monitor pc",
  "confirmation_number": "ticket",
  "contactless": "applepay tap wifi",
  "contact_mail": "address information person profile user",
  "contact_phone": "information number person profile user",
  "contacts": "address information number person phone profile user",
  "contact_support": "alert announcement bubble help information mark question speech",
  "control_camera": "adjust arrows direction left move right",
  "control_point": "circle plus",
  "control_point_duplicate": "circle plus",
  "copyright": "emblem symbol",
  "create": "item new pencil write",
  "create_new_folder": "directory",
  "credit_card": "charge creditcard finance information money payment price",
  "crop169": "image picture square",
  "crop32": "image picture square",
  "crop54": "image picture square",
  "crop75": "image picture square",
  "crop_din": "image picture square",
  "crop_free": "barcode qrcode square",
  "crop_landscape": "image picture square",
  "crop_original": "image picture square",
  "crop_portrait": "image picture square",
  "dashboard": "cards rectangle shapes square",
  "data_usage": "circle",
  "date_range": "agenda calendar event month remember reminder today week",
  "deck": "furniture garden patio",
  "delete": "bin garbage junk recycle remove trashcan",
  "delete_forever": "bin garbage junk recycle remove trashcan x",
  "delete_outline": "can garbage remove trash",
  "delete_sweep": "bin junk recycle trashcan",
  "description": "article bill document file invoice item text writing",
  "desktop_access_disabled": "apple device monitor off pc screen",
  "desktop_mac": "apple monitor pc",
  "desktop_windows": "monitor pc",
  "details": "triangle",
  "developer_board": "devkit",
  "developer_mode": "code",
  "devices": "laptop mobile phone",
  "devices_other": "smartwatch",
  "dialer_sip": "call internet phone protocol routing",
  "dialpad": "call device dots numbers phone",
  "directions": "arrow naviate",
  "directions_bike": "bicycle",
  "directions_run": "health person",
  "directions_transit": "metro subway",
  "directions_walk": "person",
  "disc_full": "cd exclamation vinyl",
  "dns": "address bars domain information ip list lookup name network server",
  "dock": "charger",
  "domain": "building",
  "domain_disabled": "building internet off website",
  "done": "checkmark complete finished success tick",
  "done_all": "checkmark complete finished multiple success tick",
  "done_outline": "checkmark complete finished success tick",
  "donut_large": "chart circle complete graph inprogress,",
  "donut_small": "chart circle",
  "double_arrow": "chevron right",
  "drafts": "email envelope letter read",
  "drag_handle": "lines",
  "drag_indicator": "circle dots drop move shape shift",
  "drive_eta": "car transport vehicle",
  "duo": "call chat conference device video",
  "dvr": "laptop monitor",
  "dynamic_feed": "live refresh update",
  "edit_location": "gps map pin write",
  "eject": "arrow player remove triangle up",
  "elderly": "old",
  "email": "envelope letter message note post receive send write",
  "emoji_emotions": "emoticon face happy like smiley",
  "emoji_food_beverage": "cup dring mug tea",
  "emoji_nature": "bee flower honey",
  "emoji_objects": "lamp lightbulb",
  "emoji_people": "man person wave waving",
  "emoji_symbols": "ampersand music note percent",
  "emoji_transportation": "building car commute company office vehicle",
  "enhanced_encryption": "lock security",
  "equalizer": "adjustment chart graph noise sound static volume",
  "error": "alert announcement circle danger exclamation feedback problem warning",
  "error_outline": "alert announcement circle danger exclamation feedback problem warning",
  "euro": "cash currency finance money price profit",
  "euro_symbol": "cash currency dollar finance money price profit",
  "event": "agenda calendar date item mark month range remember reminder today week",
  "event_available": "agenda calendar date item",
  "event_busy": "agenda calendar date item",
  "event_note": "agenda calendar date item",
  "event_seat": "assigned bench chair reservation row section sit",
  "ev_station": "car charge filling fuel gasoline power station vehicle",
  "exit_to_app": "arrow back leave login logout pointing quit right signin signup register signout",
  "expand_less": "arrow up",
  "expand_more": "arrow down",
  "explicit": "adult content language",
  "explore": "compass destination location map needle travel",
  "explore_off": "compass destination disabled location map needle travel",
  "exposure": "minus plus",
  "extension": "extended item jigsaw piece puzzle shape add-ons",
  "face": "avatar eyes human person profile thumbnail user",
  "facebook": "brand logo social",
  "fastfood": "burger drink",
  "fast_forward": "control music speed time video",
  "fast_rewind": "control music speed time video",
  "favorite": "health heart like love remember save shape success",
  "favorite_border": "health heart like love remember save shape success",
  "featured_play_list": "audio collection highlighted item music playlist recommended",
  "featured_video": "highlighted item play recommended watch,advertised",
  "feedback": "alert announcement bubble chat comment exclamation message speech",
  "fiber_dvr": "digital electronics network recorder tv video",
  "fiber_manual_record": "circle dot play watch",
  "fiber_new": "network",
  "fiber_pin": "network",
  "fiber_smart_record": "play watch",
  "file_copy": "bill invoice item page duplicate clone",
  "filter_drama": "cloud",
  "filter_hdr": "mountains",
  "filter_list": "lines",
  "filter_vintage": "flower",
  "find_in_page": "document glass look magnifying paper search see",
  "find_replace": "arrows glass inprogress look magnifying refresh rotate search see",
  "fingerprint": "biometrics identification identity reader thumbprint touchid",
  "fireplace": "flame",
  "first_page": "arrow",
  "fitness_center": "health weights workout",
  "five_g": "5g",
  "flare": "bright lensflare light shine sparkle star sun",
  "flash_auto": "lightning",
  "flash_off": "lightning",
  "flash_on": "lightning",
  "flight": "airplane flying",
  "flight_land": "airplane arrival arriving flying landing transportation travel",
  "flight_takeoff": "airplane departed departing flying landing transportation travel",
  "flip_camera_android": "front rear reverse",
  "flip_camera_ios": "front rear reverse",
  "flip_to_back": "arrangement front move order sort",
  "flip_to_front": "arrangement back move order sort",
  "folder": "directory",
  "folder_open": "directory",
  "folder_shared": "directory",
  "folder_special": "directory",
  "font_download": "letter square",
  "format_align_center": "lines",
  "format_align_justify": "lines",
  "format_align_left": "lines",
  "format_align_right": "lines",
  "format_color_fill": "bucket",
  "format_color_reset": "drop liquid water",
  "format_list_bulleted": "task todo",
  "format_list_numbered": "task todo",
  "format_list_numbered_rtl": "task todo",
  "format_paint": "paintroller",
  "format_quote": "quotation",
  "format_textdirection_l_to_r": "paragraph",
  "format_textdirection_r_to_l": "paragraph",
  "forum": "bubble chat community conversation hub messages speech talk",
  "forward": "arrow",
  "forward10": "arrow circle control fast music rotate speed time video",
  "forward30": "arrow circle control fast music rotate speed time video",
  "forward5": "arrow circle control fast music rotate speed time video",
  "four_k": "4000 display pixels resolution",
  "free_breakfast": "coffee drink tea",
  "functions": "math sigma",
  "games": "adjust arrows controller direction dpad left move nintendo playstation right xbox",
  "gavel": "court document government hammer judge law mallet official police rules",
  "gesture": "drawing line",
  "get_app": "arrow download pointing retrieve",
  "gif": "animated animation bitmap format graphics interchange",
  "git_hub": "brand code",
  "golf_course": "flag",
  "gps_fixed": "location",
  "google": "brand logo",
  "grade": "likes rated rating shape star",
  "graphic_eq": "audio equalizer",
  "grid_on": "sheet",
  "group": "people person team users",
  "group_add": "people person users",
  "group_work": "alliance circle collaboration film partnership reel teamwork together",
  "g_translate": "emblem google language logo mark speaking speech translator words",
  "hd": "definition high movies resolution tv",
  "headset": "earmuffs headphones",
  "headset_mic": "headphones",
  "healing": "bandaid health",
  "hearing": "accessibility accessible impaired listen sound",
  "height": "arrows down resize stretch up",
  "help": "alert announcement information mark question support",
  "help_outline": "alert announcement information mark question support",
  "highlight": "flashlight marker",
  "highlight_off": "circle clear click close delete disable focus remove stop target times x",
  "high_quality": "definition hq movies resolution tv",
  "history": "arrow backwards clock refresh reverse revert rotate time undo",
  "home": "address building house place residence structure unit",
  "home_work": "building house office",
  "horizontal_split": "bars stacked",
  "hotel": "bed sleep",
  "hot_tub": "jacuzzi",
  "hourglass_empty": "countdown loading minutes start time waiting",
  "hourglass_full": "countdown loading minutes time waiting",
  "http": "internet network transfer url website",
  "https": "connection encrypt internet key locked network secure security ssl web",
  "image": "picture",
  "important_devices": "cell computer monitor phone star",
  "import_contacts": "address book friends information magazine open",
  "import_export": "arrows direction down explort up",
  "indeterminate_check_box": "minus square",
  "info": "about alert announcement bubble circle information",
  "input": "arrow box right",
  "insert_chart": "barchart graph",
  "insert_comment": "chat message",
  "insert_drive_file": "bill document invoice item",
  "insert_emoticon": "emoji face happy like smiley",
  "insert_invitation": "agenda calendar",
  "insert_link": "anchor",
  "insert_photo": "image wallpaper",
  "instagram": "brand logo social",
  "invert_colors": "droplet hue inverted liquid palette tone water",
  "invert_colors_off": "droplet hue inverted liquid opacity palette tone water",
  "keyboard_arrow_down": "chevron open",
  "keyboard_arrow_left": "chevron",
  "keyboard_arrow_right": "chevron open start",
  "keyboard_arrow_up": "chevron submit",
  "keyboard_backspace": "left",
  "keyboard_capslock": "arrow",
  "keyboard_return": "arrow",
  "keyboard_tab": "arrow",
  "king_bed": "double hotel sleep",
  "kitchen": "cabinet food freezer refrigerator",
  "label": "badge indent item stamp sticker tag",
  "label_important": "badge important. indent item mail stamp sticker tag wing",
  "label_off": "indent stamp sticker tag",
  "language": "earth globe i18n l10n planet website world www country",
  "laptop_mac": "apple",
  "last_page": "arrow",
  "launch": "arrow box new open window",
  "library_add": "collection plus",
  "library_books": "add collection",
  "library_music": "add collection song",
  "line_style": "dash dotted editor rule spacing",
  "line_weight": "editor height spacing style thickness",
  "link": "anchor",
  "linked_in": "brand logo social",
  "link_off": "anchor",
  "list": "editor file format index menu task todo playlist",
  "list_alt": "box contained editor format lines reorder stacked task title todo sheet",
  "live_help": "alert announcement bubble comment faq information mark question support",
  "live_tv": "monitor television",
  "local_activity": "star",
  "local_airport": "airplane flying",
  "local_atm": "cash currency dollar financial money price profit",
  "local_bar": "alcohol drink martini",
  "local_cafe": "coffee cup drink mug",
  "local_convenience_store": "building",
  "local_dining": "cutlery knife spoon",
  "local_drink": "glass water",
  "local_florist": "flower",
  "local_gas_station": "car filling fuel gasoline station vehicle",
  "local_hospital": "aid doctor first health medical plus",
  "local_hotel": "bed sleep",
  "local_laundry_service": "clean",
  "local_library": "book person",
  "local_mall": "bag shopping",
  "local_offer": "price tag",
  "local_pharmacy": "food",
  "local_shipping": "car semi truck vehicle",
  "local_taxi": "car vehicle",
  "location_city": "building company",
  "location_off": "gps",
  "location_on": "gps",
  "lock": "connection key locked logout padlock password secure security signout",
  "lock_open": "connection key login padlock password secure security signin signup register unlocked",
  "looks": "rainbow",
  "loop": "arrows loader loading music refresh repeat rotate",
  "low_priority": "arrow list task todo",
  "loyalty": "badge card credit heart love membership miles points program sale tag travel trip",
  "mail": "envelope letter",
  "mail_outline": "email envelope letter message note post receive send write",
  "markunread": "envelope letter",
  "markunread_mailbox": "deliver envelop letter postal postbox receive send",
  "maximize": "line shape",
  "meeting_room": "door logout signout",
  "memory": "chip",
  "menu": "hamburger playlist",
  "menu_book": "page",
  "menu_open": "chevron hamburger left",
  "merge_type": "arrow",
  "message": "bubble chat comment speech talk text",
  "mic": "hearing microphone noise record sound voice",
  "mic_none": "hearing microphone noise record sound voice",
  "mic_off": "hearing microphone noise record sound voice",
  "minimize": "line shape",
  "missed_video_call": "arrow record",
  "mms": "chat comment message",
  "mobile_screen_share": "arrow device mirror monitor phone tv",
  "mode_comment": "chat message",
  "monetization_on": "cash currency dollar finance money price profit sale",
  "money": "cash currency finance price profit",
  "money_off": "cash currency dollar finance money price profit",
  "mood": "emoji emoticon face smiley",
  "mood_bad": "emoji emoticon face smiley",
  "more": "badge tag",
  "more_horiz": "dots pending status",
  "more_vert": "dots",
  "movie": "film screen show tv video watch",
  "movie_creation": "film video",
  "movie_filter": "film video",
  "multiline_chart": "analytics graph line",
  "music_video": "band recording screen tv watch",
  "nature": "forest tree",
  "nature_people": "forest person tree",
  "navigate_before": "arrow",
  "navigate_next": "arrow",
  "navigation": "arrow",
  "near_me": "arrow",
  "network_check": "wifi",
  "network_locked": "wifi",
  "new_releases": "alert announcement burst exclamation star",
  "next_week": "briefcase suitcase",
  "nights_stay": "cloud moon",
  "no_encryption": "disabled lock security",
  "no_meeting_room": "door",
  "no_sim": "camera card device eject insert memory phone storage",
  "note": "bookmark message paper",
  "note_add": "create document",
  "notification_important": "alert announcement bell feedback problem",
  "notifications": "alert bell ring",
  "notifications_active": "alert bell ring",
  "notifications_none": "alert bell ring",
  "notifications_off": "alert bell ring",
  "notifications_paused": "aleet bell ring",
  "not_interested": "allowed banned circle disabled dislike interested not off prohibited x",
  "not_listed_location": "map pin questionmark",
  "offline_bolt": "circle flash lightning spark",
  "offline_pin": "checkmark circle",
  "ondemand_video": "monitor television",
  "opacity": "color droplet hue inverted liquid palette tone water",
  "open_in_browser": "arrow box new window",
  "open_in_new": "arrow box window",
  "open_with": "arrows directional expand move",
  "outdoor_grill": "barbeque bbq",
  "pageview": "document find glass magnifying paper search",
  "palette": "color",
  "panorama": "image picture",
  "pan_tool": "drag hand human move scan stop touch wait",
  "pause": "controls music video wait status pending",
  "pause_circle_filled": "controls music video wait status pending",
  "pause_circle_outline": "controls music video wait status pending",
  "pause_presentation": "device screen share wait status pending",
  "payment": "charge creditcard financial information money price",
  "people": "group person team users",
  "people_alt": "group person users",
  "people_outline": "group person team users",
  "perm_camera_mic": "microphone photo speaker",
  "perm_contact_calendar": "agenda human person profile user",
  "perm_data_setting": "cellular configure information network settings wifi wireless",
  "perm_device_information": "alert announcement cell important mobile phone",
  "perm_identity": "human information person profile save, user",
  "perm_media": "collection directories folders images mountain save",
  "perm_phone_msg": "bubble chat message mobile recording save speech voice",
  "perm_scan_wifi": "alert announcement information internet network service wireless",
  "person": "avatar profile user",
  "person_add": "user",
  "person_add_disabled": "profile user",
  "personal_video": "monitor television",
  "person_outline": "avatar profile user",
  "person_pin": "gps location",
  "person_pin_circle": "gps location",
  "pets": "animal cat claw dog hand paw",
  "phone": "call chat device mobile text",
  "phone_android": "mobile",
  "phone_iphone": "apple mobile",
  "phonelink_erase": "device mobile",
  "phonelink_lock": "device mobile security",
  "phonelink_ring": "device mobile",
  "phonelink_setup": "device information mobile settings",
  "phone_locked": "security",
  "phone_paused": "wait",
  "photo_album": "image picture",
  "photo_camera": "image picture",
  "photo_library": "image picture",
  "picture_in_picture": "cropped overlap photo shape",
  "picture_in_picture_alt": "cropped overlap photo shape",
  "pie_chart": "analytics graph",
  "pie_chart_outlined": "graph",
  "pin_drop": "gps location",
  "pinterest": "brand logo social",
  "play_arrow": "controls music start video",
  "play_circle_filled": "arrow controls music start video",
  "play_circle_filled_white": "start",
  "play_circle_outline": "arrow controls music start video",
  "play_for_work": "arrow circle down google half",
  "playlist_add": "collection music plus task todo",
  "playlist_add_check": "checkmark collection music task tick todo",
  "playlist_play": "collection music",
  "plus_one": "add",
  "policy": "glass magnifying shield",
  "poll": "analytics barchart graph",
  "pool": "swimming water",
  "portable_wifi_off": "connected connection device internet network service usage",
  "post_add": "document item page plus",
  "power": "plug socket online",
  "power_input": "dc",
  "power_settings_new": "information off save shutdown",
  "pregnant_woman": "baby birth female human lady maternity person user",
  "present_to_all": "arrow",
  "print": "draft ink paper printer send",
  "priority_high": "exclamation",
  "public": "earth globe world country language",
  "publish": "arrow submit upload",
  "query_builder": "clock hour minute save time",
  "question_answer": "bubble chat comment conversation converse message speech talk",
  "queue": "add collection music playlist stream video",
  "queue_music": "add collection playlist stream",
  "queue_play_next": "add arrow collection device monitor music playlist plus screen video",
  "radio": "antenna device listen music player tune",
  "radio_button_checked": "circle",
  "radio_button_unchecked": "circle",
  "rate_review": "chat comment message",
  "receipt": "bill credit invoice paper payment sale transaction",
  "recent_actors": "cards carousel contacts human profile user",
  "record_voice_over": "human person profile recording sound speaking speech transcript user",
  "reddit": "brand logo social",
  "redeem": "certificate credit giftcard present",
  "redo": "arrow",
  "remove": "line minus subtract",
  "remove_circle": "allowed banned disable not",
  "remove_circle_outline": "allowed banned disable not",
  "remove_from_queue": "collection device list monitor screen television",
  "remove_shopping_cart": "checkout",
  "reorder": "format lines list stacked",
  "repeat": "arrows controls music video",
  "repeat_one": "1 arrows controls music video",
  "replay": "arrows controls music refresh reload repeat rewind undo video retry",
  "replay10": "arrows controls music repeat rewind video",
  "replay30": "arrows controls music repeat rewind video",
  "replay5": "arrows controls music repeat rewind video",
  "reply": "arrow",
  "reply_all": "arrows",
  "report": "exclamation",
  "report_problem": "alert announcement danger exclamation feedback triangle warning",
  "restaurant": "cutlery fork knife",
  "restore": "arrow backwards clock history refresh reverse rotate time undo",
  "restore_from_trash": "arrow can delete garbage remove up",
  "restore_page": "arrow history paper refresh rotate undo web",
  "ring_volume": "mobile phone",
  "room": "gps location map marker pin place spot",
  "room_service": "bell concierge",
  "rotate90_degrees_ccw": "arrow",
  "rotate_left": "arrow circle refresh reload reset",
  "rotate_right": "arrow circle",
  "rounded_corner": "shape square transform",
  "router": "device network",
  "rowing": "activity boat canoe human person sports water",
  "rss_feed": "network wifi",
  "save": "diskette floppy write",
  "save_alt": "diskette floppy write",
  "scanner": "device",
  "schedule": "calendar clock date mark save time",
  "school": "college university",
  "screen_lock_landscape": "mobile phone security",
  "screen_lock_portrait": "mobile phone security",
  "screen_lock_rotation": "mobile phone",
  "screen_rotation": "mobile phone",
  "screen_share": "laptop monitor",
  "sd_storage": "microsd",
  "search": "filter find glass look magnifying up",
  "security": "shield",
  "send": "chat message telegram",
  "sentiment_dissatisfied": "emoji emoticon sad smiley",
  "sentiment_satisfied": "emoji emoticon happy like smiley",
  "sentiment_very_dissatisfied": "emoji emoticon sad smiley unhappy",
  "sentiment_very_satisfied": "emoji emoticon happy like smiley",
  "settings": "gear",
  "settings_applications": "details gear information personal save service",
  "settings_backup_restore": "arrow backwards history refresh reverse rotate time undo",
  "settings_bluetooth": "connection connectivity network wifi",
  "settings_brightness": "dark light mode sun",
  "settings_cell": "cellphone device mobile",
  "settings_ethernet": "arrows brackets connection connectivity dots network parenthesis wifi",
  "settings_input_antenna": "connection connectivity network wifi",
  "settings_input_component": "cable connection connectivity plugs points",
  "settings_input_composite": "cable component connection connectivity plugs points",
  "settings_input_hdmi": "cable connection connectivity plugin points",
  "settings_input_svideo": "connection connectivity plugin plugs points svideo,",
  "settings_overscan": "arrows expand image photo picture",
  "settings_phone": "cell device mobile",
  "settings_power": "information off save shutdown",
  "settings_remote": "bluetooth control wifi",
  "settings_system_daydream": "cloud",
  "settings_voice": "microphone recorder speaker",
  "shop": "arrow briefcase buy cart google play purchase shopping",
  "shopping_basket": "add buy cart purchase",
  "shopping_cart": "add buy checkout purchase",
  "shop_two": "arrow briefcase buy cart google play purchase shopping",
  "short_text": "lines",
  "show_chart": "analytics graph line stock",
  "shuffle": "arrows controls music video",
  "signal_cellular_4_bar": "network",
  "signal_cellular_connected_no_internet_0_bar": "network",
  "signal_cellular_connected_no_internet_1_bar": "network",
  "signal_cellular_connected_no_internet_2_bar": "network",
  "signal_cellular_connected_no_internet_3_bar": "network",
  "signal_cellular_connected_no_internet_4_bar": "network",
  "signal_cellular_no_sim": "network",
  "signal_cellular_null": "network",
  "signal_cellular_off": "network",
  "signal_wifi_0_bar": "network",
  "signal_wifi_1_bar": "network",
  "signal_wifi_4_bar": "network",
  "signal_wifi_4_bar_lock": "network",
  "signal_wifi_off": "network",
  "sim_card": "network",
  "single_bed": "hotel queen sleep",
  "skip_next": "arrow back controls music play previous video",
  "skip_previous": "arrow controls forward music next play video",
  "slideshow": "presentation",
  "slow_motion_video": "arrow circle controls music play time",
  "smartphone": "mobile",
  "smoke_free": "cigarette",
  "smoking_rooms": "cigarette",
  "sms": "chat comment message",
  "sms_failed": "chat comment message",
  "snooze": "alarm clock set timer",
  "sort": "lines",
  "sort_by_alpha": "alphabetize letters list order organize",
  "spa": "flower",
  "speaker": "audio",
  "speaker_group": "audio",
  "speaker_notes": "bubble cards chat comment format list message speech",
  "speaker_notes_off": "bubble cards chat comment format list message speech",
  "speaker_phone": "mobile",
  "speed": "clock dial measure test",
  "spellcheck": "alphabet checkmark edit letter processor word write",
  "sports": "whistle",
  "sports_esports": "controller gamepad playstation xbox",
  "sports_football": "american",
  "sports_hockey": "ice",
  "sports_kabaddi": "fighting judo martial",
  "sports_soccer": "football",
  "star": "rating",
  "star_border": "rating",
  "star_half": "rating",
  "stars": "circle favorite like love rate rating",
  "stay_current_landscape": "mobile phone",
  "stay_current_portrait": "mobile phone",
  "stay_primary_landscape": "mobile phone",
  "stay_primary_portrait": "mobile phone",
  "stop": "arrow controls music play square video",
  "stop_screen_share": "laptop monitor",
  "storage": "database network server",
  "store": "building buy e-commerce purchase shop storefront",
  "storefront": "merchant shop stall",
  "store_mall_directory": "building",
  "straighten": "piano",
  "streetview": "gps location map",
  "subdirectory_arrow_left": "arrow",
  "subdirectory_arrow_right": "arrow",
  "subject": "document email full justify lines list note text writing",
  "subscriptions": "enroll order playlist queue subscribe youtube",
  "subtitles": "accessibility accessible captions language translate",
  "subway": "metro",
  "supervised_user_circle": "avatar human people person profile supervisor",
  "supervisor_account": "administrator avatar human people person profile supervised user",
  "surround_sound": "audio circle speaker system volume",
  "swap_calls": "arrow",
  "swap_horiz": "arrows back direction horizontal",
  "swap_horizontal_circle": "arrows back direction",
  "swap_vert": "arrows back direction vertical",
  "swap_vertical_circle": "arrows back direction horizontal",
  "sync": "arrows refresh",
  "sync_alt": "arrows",
  "sync_disabled": "arrows refresh",
  "sync_problem": "arrows refresh",
  "system_update": "arrow download",
  "system_update_alt": "arrow download",
  "tablet_mac": "apple",
  "tap_and_play": "nfc wifi",
  "telegram": "brand call chat logo messaging voice",
  "text_format": "letter",
  "text_rotate_up": "arrow field move",
  "text_rotate_vertical": "arrow field move verticle",
  "text_rotation_angledown": "arrow field move rotate",
  "text_rotation_angleup": "arrow field move rotate",
  "text_rotation_down": "arrow field move rotate",
  "text_rotation_none": "arrow field move rotate",
  "textsms": "chat comment message",
  "theaters": "media movies photography showtimes video watch",
  "three_d_rotation": "3d arrows vr",
  "thumb_down": "dislike favorite finger hand rate rating reject up vote",
  "thumb_down_alt": "dislike hand reject vote",
  "thumbs_up_down": "dislike favorite finger hand rate rating vote",
  "thumb_up": "approve dislike down favorite finger hand rate rating success vote",
  "thumb_up_alt": "approve hand like success vote",
  "timeline": "analytics chart graph history line movement points trending zigzap",
  "timer": "clock stopwatch wait",
  "timer_off": "clock stopwatch",
  "tips_and_updates": "bulb lamp light",
  "toc": "content format lines list reorder stacked table text titles",
  "today": "agenda calendar date event mark month range remember reminder week",
  "toll": "booth car circles payment ticket",
  "touch_app": "arrow finger gesture hand swipe",
  "toys": "fan",
  "track_changes": "bullseye circle evolve lines movement radar rotate shift target",
  "traffic": "light",
  "transfer_within_a_station": "man person transit",
  "translate": "alphabet language letter speaking speech text translator words",
  "trending_down": "arrow change chart graph metric movement rate sale tracking",
  "trending_flat": "arrow change chart graph metric movement rate tracking",
  "trending_up": "arrow change chart graph metric movement rate tracking",
  "tune": "settings sliders",
  "turned_in": "bookmark item remember save submit",
  "turned_in_not": "bookmark item outline remember save submit",
  "tv": "television",
  "twitter": "brand logo social",
  "two_wheeler": "bicycle moped motorbike ride riding transportation vehicle wheels",
  "unarchive": "arrow",
  "undo": "arrow",
  "unfold_less": "arrow",
  "unfold_more": "arrow",
  "update": "arrow backwards clock future history refresh reverse rotate time",
  "verified_user": "audit certified checkmark security shield",
  "vertical_align_bottom": "arrow",
  "vertical_align_center": "arrow",
  "vertical_align_top": "arrow",
  "vertical_split": "format paragraph text website",
  "vibration": "mobile phone",
  "video_call": "camera chat conference plus screen",
  "videocam": "camera chat conference screen",
  "videocam_off": "camera chat conference screen",
  "videogame_asset": "controller gamepad nintendo playstation xbox",
  "video_label": "device item screen",
  "video_library": "collection",
  "view_agenda": "blocks cards format website,stacked",
  "view_array": "blocks format website",
  "view_carousel": "banner blocks cards format images",
  "view_column": "blocks format grid vertical website",
  "view_comfy": "grid",
  "view_compact": "grid",
  "view_day": "blocks calendar cards carousel format week",
  "view_headline": "blocks format paragraph text website",
  "view_list": "blocks format lines reorder stacked title",
  "view_module": "blocks format reorder squares stacked title",
  "view_quilt": "blocks format reorder squares stacked title",
  "view_stream": "blocks format lines list reorder stacked title",
  "view_week": "bars blocks columns day format",
  "vignette": "effect photo",
  "visibility": "eye on password reveal see shown view visability preview",
  "visibility_off": "eye hidden invisible on password reveal see show view visability",
  "voice_chat": "camera",
  "volume_down": "control sound",
  "volume_mute": "control sound",
  "volume_off": "control sound",
  "volume_up": "control sound",
  "vpn_key": "login password security signin signup register",
  "vpn_lock": "earth globe password security world",
  "wallpaper": "image picture",
  "warning": "alert announcement danger error exclamation feedback problem triangle",
  "watch": "smartwatch",
  "watch_later": "clock hour minute time",
  "wb_incandescent": "lamp lightbulb",
  "wb_sunny": "weather",
  "wc": "gender person toilet unisex gender",
  "web": "blocks browser internet screen website www",
  "web_asset": "browser download image internet screen video website www",
  "weekend": "chair couch seat",
  "whats_app": "brand call chat logo messaging voice",
  "whatshot": "fire trending",
  "widgets": "blocks",
  "wifi": "network",
  "wifi_lock": "network",
  "wifi_tethering": "network",
  "work": "briefcase job suitcase",
  "work_off": "briefcase job suitcase",
  "work_outline": "briefcase job suitcase",
  "wrap_text": "arrow",
  "you_tube": "brand logo social video",
  "youtube_searched_for": "arrow backwards refresh restore reverse rotate",
  "zoom_in": "bigger glass grow magnifier magnifying plus scale size",
  "zoom_out": "glass magnifier magnifying minus negative scale size smaller",
  "zoom_out_map": "arrows"
};

export default synonyms;
